# Generated by Django 4.2.24 on 2025-11-14 15:24

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone number')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country')),
                ('department', models.CharField(choices=[('0', 'IT'), ('1', 'HR'), ('2', 'Sales'), ('3', 'Finiance'), ('4', 'Management')], default='2', max_length=32, verbose_name='Department')),
                ('birth_date', models.DateField(verbose_name='Birthday')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Salary')),
                ('password', models.CharField(help_text='Hashed password', max_length=255, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='Password')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is user active?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff?')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateField(auto_now=True, verbose_name='last_login')),
                ('role', models.CharField(choices=[('0', 'Admin'), ('1', 'Manager'), ('2', 'employee')], default='2', max_length=32, verbose_name='Role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'ordering': ['-email'],
            },
        ),
    ]
