# Generated by Django 4.2.24 on 2025-11-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
    ]
