# Generated by Django 4.2.24 on 2025-11-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('SLS', 'Sales'), ('FNC', 'Finiance'), ('MNG', 'Management')], default='2', max_length=32, verbose_name='Department'),
        ),
    ]
