# Generated by Django 4.2.24 on 2025-10-05 14:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.CharField(choices=[(0, 'NEW'), (1, 'CONFIRMED'), (2, 'COOK'), (2, 'DELIVERY'), (3, 'DONE')], max_length=32, verbose_name='Статус')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Сумма без скидок')),
                ('discount_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Итоговая скидка')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Итоговая сумма')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.address')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
                'default_related_name': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=32, verbose_name='Название блюда')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.99)], verbose_name='Цена')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.order')),
            ],
            options={
                'verbose_name': 'товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
                'default_related_name': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Скидка в %')),
                ('is_active', models.BooleanField(verbose_name='Действует сейчас?')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'Промокоды',
                'default_related_name': 'promocodes',
            },
        ),
        migrations.CreateModel(
            name='Order_Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.order')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.promocode')),
            ],
            options={
                'verbose_name': 'промокод заказа',
                'verbose_name_plural': 'Промокоды заказа',
                'default_related_name': 'order_promocodes',
            },
        ),
        migrations.CreateModel(
            name='Order_Item_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=256, verbose_name='Название')),
                ('price_delta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Разница в цене')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerces.order_item')),
            ],
            options={
                'verbose_name': 'опция к товару',
                'verbose_name_plural': 'Опции к товару',
                'default_related_name': 'item_options',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promocodes',
            field=models.ManyToManyField(through='commerces.Order_Promo', to='commerces.promocode'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='order_promo',
            constraint=models.UniqueConstraint(fields=('order', 'promocode'), name='unique_promo_order_pair'),
        ),
    ]
