# Generated by Django 4.2.24 on 2025-10-05 14:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=256, verbose_name='Город')),
                ('street', models.CharField(max_length=256, verbose_name='Улица')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('additional_info', models.TextField(verbose_name='Дополнительная информация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'Адреса',
                'default_related_name': 'adresses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'кухня',
                'verbose_name_plural': 'Кухни',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.99)], verbose_name='Цена')),
                ('is_available', models.BooleanField()),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['price'],
                'default_related_name': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.address')),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.cuisine')),
            ],
            options={
                'verbose_name': 'ресторан',
                'verbose_name_plural': 'Рестораны',
                'default_related_name': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='Option_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_delta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Разница в цене')),
                ('is_default', models.BooleanField(verbose_name='По умолчанию?')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.menuitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.option')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='options',
            field=models.ManyToManyField(through='catalogs.Option_Item', to='catalogs.option'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.restaurant'),
        ),
        migrations.CreateModel(
            name='Category_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.category')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='menu_items',
            field=models.ManyToManyField(through='catalogs.Category_Item', to='catalogs.menuitem'),
        ),
        migrations.AddConstraint(
            model_name='option_item',
            constraint=models.UniqueConstraint(fields=('option', 'menu_item'), name='unique_option_item_pair'),
        ),
        migrations.AddConstraint(
            model_name='category_item',
            constraint=models.UniqueConstraint(fields=('category', 'menu_item'), name='unique_category_item_pair'),
        ),
    ]
